package dev.femrek.reactadmindataprovider.config;

import org.springdoc.core.customizers.OpenApiCustomizer;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.context.annotation.Bean;

import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * Configuration class that customizes the OpenAPI documentation generated by springdoc-openapi.
 *
 * <p>This configuration specifically addresses the issue of duplicate "Objects" tags appearing
 * in the API documentation when controllers extend the base RAController class.
 *
 * <p>The tag cleanup logic operates as follows:
 * <ol>
 *   <li>Iterate through all operations in the OpenAPI specification</li>
 *   <li>For operations with both the "Objects" tag and other specific tags, remove the generic
 *       "Objects" tag to avoid duplication</li>
 *   <li>Operation IDs are updated to include the resource name. Operations that semantically
 *       act on a single entity use a singularized tag (e.g., {@code getPost}), while operations
 *       that act on multiple entities keep the plural tag (e.g., {@code listPosts}).</li>
 *   <li>For operations with only the "Objects" tag, keep it and mark that the global tag
 *       definition should be retained</li>
 *   <li>After processing all operations, if the generic tag was never used alone, remove the
 *       global tag definition to clean up the documentation</li>
 * </ol>
 *
 * <p>This ensures that "Objects" appears only once in the API documentation and is only
 * present where it is truly needed.
 *
 * @see org.springdoc.core.customizers.OpenApiCustomizer
 */
@SuppressWarnings({"GrazieInspection", "SpellCheckingInspection"})
@AutoConfiguration
public class RAOpenApiConfig {
    private static final String GENERIC_TAG = "Objects";

    /**
     * Operation IDs from {@link dev.femrek.reactadmindataprovider.controller.IRAController} that
     * act on a <em>single</em> resource. When building the final operation ID, the tag name will
     * be singularized (e.g., tag "Posts" → "Post", so the ID becomes "getPost").
     */
    private static final Set<String> SINGULAR_OPERATION_IDS = Set.of(
            "get",
            "create",
            "update",
            "delete"
    );

    /**
     * Operation IDs from {@link dev.femrek.reactadmindataprovider.controller.IRAController} that
     * act on <em>multiple</em> resources. The tag name is kept in its original (typically plural)
     * form when building the final operation ID (e.g., tag "Posts" stays "Posts", so the ID
     * becomes "listPosts").
     */
    private static final Set<String> PLURAL_OPERATION_IDS = Set.of(
            "list",
            "getMany",
            "getManyReferenceBy",
            "updateMany",
            "deleteMany"
    );

    /**
     * Irregular plural-to-singular mappings that cannot be derived by simple suffix rules.
     */
    private static final Map<String, String> IRREGULAR_PLURALS = Map.of(
            "people", "person",
            "men", "man",
            "women", "woman",
            "children", "child",
            "teeth", "tooth",
            "feet", "foot",
            "mice", "mouse",
            "geese", "goose",
            "oxen", "ox",
            "criteria", "criterion"
    );

    /**
     * Converts a plural word to its singular form using common English suffix rules and a small
     * table of irregular forms.
     *
     * <p>Rules applied (in order):
     * <ol>
     *   <li>Irregular forms (e.g., "people" → "person")</li>
     *   <li>Words ending in "ies" → replace with "y" (e.g., "categories" → "category")</li>
     *   <li>Words ending in "ses", "xes", "zes", "ches", "shes" → remove "es"
     *       (e.g., "boxes" → "box")</li>
     *   <li>Words ending in "ves" → replace with "f" (e.g., "leaves" → "leaf")</li>
     *   <li>Words ending in "s" (but not "ss") → remove "s" (e.g., "posts" → "post")</li>
     *   <li>Otherwise return the word unchanged</li>
     * </ol>
     *
     * <p>Only the last word segment is singularized when the input is camelCase or PascalCase;
     * the prefix is preserved.
     *
     * @param word the word (or PascalCase/camelCase tag name) to singularize
     * @return the singular form of the word, or the original if no rule applies
     */
    @SuppressWarnings("DuplicateExpressions")
    static String toSingular(String word) {
        if (word == null || word.isEmpty()) return word;

        // Preserve leading camelCase prefix (e.g., "myPosts" → prefix="my", base="Posts")
        // We only singularize the base (last capitalized segment or the whole word).
        // For simplicity, work on the whole word and preserve case of the first character.
        String lower = word.toLowerCase();

        // Check irregular forms first
        for (Map.Entry<String, String> entry : IRREGULAR_PLURALS.entrySet()) {
            if (lower.endsWith(entry.getKey())) {
                int prefixLen = word.length() - entry.getKey().length();
                String singular = entry.getValue();
                // Restore capitalization of the singular suffix to match the original word's case
                if (prefixLen < word.length() && Character.isUpperCase(word.charAt(prefixLen))) {
                    singular = Character.toUpperCase(singular.charAt(0)) + singular.substring(1);
                }
                return word.substring(0, prefixLen) + singular;
            }
        }

        // Words ending in "ies" → "y"  (e.g., Categories → Category)
        if (lower.endsWith("ies") && word.length() > 3) {
            return word.substring(0, word.length() - 3) + matchCase(word, word.length() - 3, "y");
        }

        // Words ending in "ses", "xes", "zes", "ches", "shes" → remove "es"
        if (lower.endsWith("ses") || lower.endsWith("xes") || lower.endsWith("zes")
                || lower.endsWith("ches") || lower.endsWith("shes")) {
            return word.substring(0, word.length() - 2);
        }

        // Words ending in "ves" → "f"  (e.g., Leaves → Leaf)
        if (lower.endsWith("ves") && word.length() > 3) {
            return word.substring(0, word.length() - 3) + matchCase(word, word.length() - 3, "f");
        }

        // Words ending in "s" but not "ss"
        if (lower.endsWith("s") && !lower.endsWith("ss")) {
            return word.substring(0, word.length() - 1);
        }

        return word;
    }

    /**
     * Returns {@code suffix} with its first character uppercased if the character at
     * {@code referenceIndex} in {@code word} is uppercase, otherwise returns {@code suffix} as-is.
     */
    private static String matchCase(String word, int referenceIndex, String suffix) {
        if (referenceIndex >= 0 && referenceIndex < word.length()
                && Character.isUpperCase(word.charAt(referenceIndex))) {
            return Character.toUpperCase(suffix.charAt(0)) + suffix.substring(1);
        }
        return suffix;
    }

    @Bean
    public OpenApiCustomizer removeDuplicateGenericTag() {
        return openApi -> {
            AtomicBoolean isGenericTagUsedAlone = new AtomicBoolean(false);

            // Clean operations AND check if generic tag is needed
            openApi.getPaths().values().stream()
                    .flatMap(pathItem -> pathItem.readOperations().stream())
                    .forEach(operation -> {
                        List<String> tags = operation.getTags();

                        if (tags != null && tags.contains(GENERIC_TAG)) {
                            if (tags.size() > 1) {
                                // CASE 1: Generic tag + Specific tag exist.
                                // Remove generic tag. It is NOT "used alone" here.
                                tags.remove(GENERIC_TAG);

                                // Update operation ID using the resource tag name.
                                // Singular operations: singularize the tag (getPost, createPost, …)
                                // Plural  operations: keep the tag as-is  (listPosts, getManyPosts, …)
                                String resourceTag = tags.get(0);
                                String currentOperationId = operation.getOperationId();
                                if (resourceTag != null && currentOperationId != null) {
                                    String resourceName;
                                    if (SINGULAR_OPERATION_IDS.contains(currentOperationId)) {
                                        // Singular operations: singularize the tag (e.g., "Posts" → "Post")
                                        resourceName = toSingular(resourceTag);
                                        operation.setOperationId(currentOperationId + resourceName);
                                    } else if (PLURAL_OPERATION_IDS.contains(currentOperationId)) {
                                        // Plural operations: keep the tag as-is (e.g., "Posts" stays "Posts")
                                        resourceName = resourceTag;
                                        operation.setOperationId(currentOperationId + resourceName);
                                    }
                                }
                            } else {
                                // CASE 2: Only Generic tag exists.
                                // We must keep it, and we mark that the global definition is still needed.
                                isGenericTagUsedAlone.set(true);
                            }
                        }
                    });

            // Final Step: If we never found the generic tag "standing alone", remove the global definition
            if (!isGenericTagUsedAlone.get() && openApi.getTags() != null) {
                openApi.getTags().removeIf(tag -> GENERIC_TAG.equals(tag.getName()));
            }
        };
    }
}
